spring:
  application:
    name: Spring Batch
  datasource:
    username: YOUR_USER_NAME
    password: YOUR_PASSWORD
    url: jdbc:postgresql://localhost:5432/spring_batch
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
  batch:
    jdbc:
      initialize-schema: always
    #disabled job run at startup
    job:
      enabled: false
server:
  port: 8082
